AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'app/assets/**/*'
    - 'app/assets/javascripts/*'
  DisplayCopNames: true
  RunRailsCops: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 20